steps:
  - label: ":nixos: :rust: check"
    command: RUSTFLAGS="-D warnings" nix develop --command bash -c "cargo check"
    agents:
      queue: nixos

  - label: ":nixos: :rust: clippy"
    command: RUSTFLAGS="-D warnings" nix develop --command bash -c "cargo clippy"
    agents:
      queue: nixos

  - label: ":nixos: :rust: test"
    command: RUSTFLAGS="-D warnings" nix develop --command bash -c "cargo test"
    agents:
      queue: nixos

  - label: ":nixos: :rust: fmt"
    command: RUSTFLAGS="-D warnings" nix develop --command bash -c "cargo fmt --check"
    agents:
      queue: nixos

  - label: ":nixos: :rust: doc"
    command: nix develop --command bash -c "cargo doc --no-deps --workspace"
    agents:
      queue: nixos
      
  - label: ":nixos: :rust: taplo"
    command: nix develop --command bash -c "taplo fmt --check"
    agents:
      queue: nixos
      
  - label: ":nixos: :rust: semver-checks"
    command: nix develop --command bash -c "cargo semver-checks"
    agents:
      queue: nixos

  - label: ":nixos: :rust: bench"
    command: nix develop --command bash -c "cargo bench"
    agents:
      queue: nixos
