[hunspell]
lang = "en_US"
search_dirs = [ "." ]
extra_dictionaries = [ "lingua.dic" ]
skip_os_lookups = true
use_builtin = true

[hunspell.quirks]
# He tagged it as 'TheGreatestOfAllTimes'
transform_regex = [
	# `Type`'s
	"^'([^\\s])'$",
	# 5x
	# 10.7%
	"^[0-9_]+(?:\\.[0-9]*)?(x|%)$",
	# Transforms'
	"^(.*)'$",
	# backslashes
	"^\\+$",
	"^[0-9]*+\\s?k|MB|Mb|ms|Mbit|nd|th|rd|s$",
	# single char `=` `>` `%` ..
	"^=|>|<|%$",
	# 22_100
	"^(?:[0-9]+_)+[0-9]+$",
	# We use { a or b } for { p or q }.
	"^\\{(.*)\\}$",
]
allow_concatenation = true
allow_dashes = true
